version: "3.8"
services:
  # mongodb:
  #   image: "mongo"
  #   volumes:
  #     - data:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: max
  #     MONGO_INITDB_ROOT_PASSWORD: secret

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    # volumes:
    #   - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    container_name: max-mern-mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    # env_file:
    #   - ./env/mongo.env
    # networks:
    #   - mern-network
  backend:
    # build: 
    #   context: ./backend
    #   dockerfile: dockerfile
    build: ./backend
    container_name: max-mern-backend
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
    ports: 
      - 80:80
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: max-mern-frontend
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - backend

# volumes:
#   data:
